//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrder()
        {
            this.tblOrderItems = new HashSet<tblOrderItem>();
        }
    
        public int OrderID { get; set; }
        public System.DateTime DateTimeOrder { get; set; }
        public int Guest { get; set; }
        public int TotalPrice { get; set; }
        public int OrderStatus { get; set; }
        public int Archived { get; set; }

        public string Status
        {
            get
            {
                if (OrderStatus == 2)
                {
                    return "Approved";
                }
                else if (OrderStatus == 3)
                {
                    return "Discarded";
                }
                else
                {
                    return "On hold";
                }
            }
        }

        public virtual tblGuest tblGuest { get; set; }
        public virtual tblOrderStatu tblOrderStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderItem> tblOrderItems { get; set; }
    }
}
