//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderItem
    {
        public int OrderItemID { get; set; }
        public int ProductName { get; set; }
        public int ProductPrice { get; set; }
        public int ProductQuantity { get; set; }
        public int OrderName { get; set; }
        public int OrderSum { get; set; }
    
        public virtual tblOrder tblOrder { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
