//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwOrder
    {
        public int OrderItemID { get; set; }
        public int ProductName { get; set; }
        public int ProductPrice { get; set; }
        public int ProductQuantity { get; set; }
        public int OrderName { get; set; }
        public int OrderID { get; set; }
        public System.DateTime DateTimeOrder { get; set; }
        public int Guest { get; set; }
        public int TotalPrice { get; set; }
        public int Archived { get; set; }
        public int OrderStatus { get; set; }
        public int GuestID { get; set; }
        public string GuestName { get; set; }
        public string GuestSurname { get; set; }
        public string JMBG { get; set; }
        public string EMail { get; set; }
        public int OrderStatusID { get; set; }
        public string Expr1 { get; set; }
        public int ProductID { get; set; }
        public string ProductDescription { get; set; }
        public int CategoryName { get; set; }
        public string Expr2 { get; set; }
        public int PriceProduct { get; set; }
        public int CategoryID { get; set; }
        public string Expr3 { get; set; }
        public int OrderSum { get; set; }

        public string Details
        {
            get
            {
                return $" > {Expr2}/{Expr3}/{ProductQuantity}x/{ProductPrice}";

            }
        }

        public string Header
        {
            get
            {
                return $"Order {OrderName}\n{Expr1}>{DateTimeOrder} / TotalSum: {TotalPrice},00 RSD";

            }
        }

        public string HeaderHoldOn
        {
            get
            {
                return $"Order {OrderName}\nStatus: {Expr1}\nDate&Time: {DateTimeOrder}\nTotalSum: {TotalPrice},00 RSD";

            }
        }
    }
}
